# Test your FastAPI endpoints

GET http://127.0.0.1:3005/
Accept: application/json

###

GET http://127.0.0.1:3005/hello/User
Accept: application/json

###
GET http://127.0.0.1:3005/home/0
Accept: application/json
